@host = http://127.0.0.1:8080/v1


### Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Token verification
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzODI3NDE4fQ.iChBcwWwU1A1ScQa1eGU0KyYWzGflAA7dS1bOl760hI

GET {{host}}/verify-token?token={{token}} HTTP/1.1

