@host = http://127.0.0.1:6000


###
GET {{host}}/v1/cats/ HTTP/1.1

###
DELETE  {{host}}/v1/cats/1 HTTP/1.1

###
POST {{host}}/v1/cats/ HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Alpha Meow"
}

###
GET {{host}}/v1/cats/ HTTP/1.1

###
DELETE  {{host}}/v1/cats/1 HTTP/1.1

###
POST {{host}}/v1/cats/ HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Alpha Aww"
}